### ISSUE TITLE
Duplicated vscode folder.

### ISSUE THREAD

**Issue by phamhongphuc** [ngdph/email-client-schoolapp#4]
You shouldn't commit the `.vscode` folder to source control.
If you still want to share it, you should not make it duplicated. (`<root>/.vscode` and `<root>/source/.vscode`)

**Comment by ngdph** [comment]
> You shouldn't commit the `.vscode` folder to source control.
> If you still want to share it, you should not make it duplicated. (`<root>/.vscode` and `<root>/source/.vscode`)

Thanks for your ideas, this is just a little school project so I don't give much care about it. `.vscode` directory and other things will be ignored in other projects.
